### ISSUE TITLE
[Enhancement] When blank results are returned, return something( Was: when no data is found no results are found either)

### ISSUE THREAD

**Issue by LevitSmith** [KelvinTegelaar/AutotaskAPI#11]
**Describe the bug**
when running get-autotastapiresource -resource tickets and I list a fake id, no data is returned at all. 

**To Reproduce**
1. get-autotaskapiresource
2. get-autotaskapiresource - resource tickets -simplesearch  id eq 123343
3. further info
4. Error code

**Expected behavior**
return  no results found or something alike

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 /
 - PowerShell version: 7
 - Version 0.9.7

**Additional context**

**Comment by KelvinTegelaar** [comment]
I understand what you're saying, but I'm not sure if its a bug. I'm reclassifying this as a feature enhancement.

I understand the usability aspect of it so expect this to be in the final release, in some form of the other. :)

**Comment by KelvinTegelaar** [comment]
Hi Levit,

After discussion with some other developers I've decided to make this a won't fix. You can see if the cmdlet is working by adding -verbose. Blank data should be $null so you can act according to that.
