### ISSUE TITLE
[BUG] New-Autotaskbody does not return possibe UDFs

### ISSUE THREAD

**Issue by TimHolmesNY** [KelvinTegelaar/AutotaskAPI#12]
**Describe the bug**
When retrieving a new body, there are no UDF options included. We've made getting those UDFs easy. It can be done by calling entityInformation/userdefinedfields.

**Comment by KelvinTegelaar** [comment]
Thanks for reporting this Tim, I did not realize and it was an easy fix. Now found in the beta build :)

Ps: Tim from Datto? ;)
