### ISSUE TITLE
[BUG] Module only works on Windows

### ISSUE THREAD

**Issue by klemmestad** [KelvinTegelaar/AutotaskAPI#16]
`[System.Runtime.InteropServices.Marshal]::PtrToStringAuto()` does not work as expected on other platforms than Windows. It only returns the first character of the secret. Switch to `[System.Runtime.InteropServices.Marshal]::PtrToStringBSTR()` to solve the problem. This behavior is as expected, on Windows any string defaults to UTF-16 which is what BSTRs are, on other platform strings defaults to UTF-8 which causes this problem. [See a more detailed explanation here](https://github.com/PowerShell/PowerShell/issues/12114)

**Symptoms**
Any API call fails as "unauthorized". When debugging you'll notice that $secret is only 1 character long, i.e. the users password is not passed along correctly to the API.

**Solution**
Change AutoTaskAPI.psm1:125 to
```powershell
    $Secret = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($BSTR)
```

**Desktop (please complete the following information):**
 - OS: OSX
 - PowerShell version: V7

**Additional context**
I couldn't figure out how to open a pull request from VSCode. A permission issue? So I posted the suggested change here instead 😊

**Comment by KelvinTegelaar** [comment]
Added you as a direct collaborator :) Try another pull request to check. :)

**Comment by klemmestad** [comment]
Thank you! Checked in the change just fine! Closing this issue... ;)
