### ISSUE TITLE
[BUG]Issue Retrieving the Webservices URI based on Username

### ISSUE THREAD

**Issue by markrj66** [KelvinTegelaar/AutotaskAPI#17]
When running Add-AutotaskAPIAuth I get the error showing in the screenshot.

I have tried running  Add-AutotaskBaseURI -BaseURI https://webservices16.autotask.net/atservicesrest and running again but the message is the same whatever URI I use.

I have tested with Postman and can connect successfully with the same credentials

![Annotation 2020-07-08 130356](https://user-images.githubusercontent.com/37551757/86916456-88b40b80-c11b-11ea-9164-e5de67b39529.png)

**Comment by KelvinTegelaar** [comment]
Can you try browsing to https://webservices2.autotask.net/atservicesrest/v1.0/zoneInformation?user=<YOUREMAILHERE> and see if you get a correct zone returned?

**Comment by markrj66** [comment]
Hi Kelvin,

No I get the following message - {"errors":["Zone information could not be determined"]}

**Comment by KelvinTegelaar** [comment]
I've just uploaded a version to the PsGallery with some slight improvements to this, can you try following:

update-module AutotaskAPI -Force
Add-AutotaskAPIAuth (This will fill as autodiscover is not working for your account)
Add-AutotaskBaseURI -BaseURI "https://webservices16.autotask.net/atservicesrest"

you should then be able to perform something like
```
Get-AutotaskAPIResource -Resource companies -SimpleSearch 'isActive eq true'
```

**Comment by markrj66** [comment]
Hi Kelvin,

Yes this now works, I still get the error 500 when running the Add-AutotaskAPIAuth command but I can access the data.

Thanks for your help

**Comment by KelvinTegelaar** [comment]
No problem. Glad it's working.
