### ISSUE TITLE
[BUG] Cannot create Projects

### ISSUE THREAD

**Issue by AaronICT** [KelvinTegelaar/AutotaskAPI#35]
When trying to create a project I'm getting the following error:

     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Connecting to the Autotask API failed. Response status code does not indicate success: 500 (Internal Server Error).

Here is the code:
$Body = New-AutotaskBody -Resource Projects
$Body.companyID = 184 #Sea Island
$Body.createDateTime = Get-Date '3/25/2022 12:00:00 AM'
$Body.creatorResourceID = 29682885
$Body.description = "test"
$Body.endDateTime = Get-Date '6/30/2022 12:00:00 AM'
$Body.projectLeadResourceID = 29682885
$Body.projectName = "test"
$Body.projectType = 5
$Body.startDateTime = Get-Date '3/25/2022 12:00:00 AM'
$Body.status = 2 #in progress
New-AutotaskAPIResource -Resource Projects -Body $Body

I can retrieve Projects with no issues, but I can't create them.

Am I doing something wrong?
Thanks
Aaron

**Comment by AaronICT** [comment]
Looks like there are a bunch more required fields that what is in the Autotask documentation. These are all the fields that see to be required (at least for me).

$Body.id =0
$Body.actualBilledHours = 0
$Body.actualHours = 0
$Body.companyID = 184
$Body.completedPercentage = 0
$Body.createDateTime = Get-Date '3/25/2022 12:00:00 AM'
$Body.creatorResourceID = 29682885
$Body.description = 'test'
$Body.duration = 0
$Body.endDateTime = Get-Date '6/30/2022 12:00:00 AM'
$Body.estimatedTime = 0
$Body.lastActivityDateTime = Get-Date '3/25/2022 3:52:31 PM'
$Body.lastActivityPersonType = 1
$Body.lastActivityResourceID = 29682885
$Body.projectName = 'test'
$Body.projectType = 5
$Body.startDateTime = Get-Date '3/25/2022 12:00:00 AM'
$Body.status = 2
$Body.userDefinedFields = $null

**Comment by KelvinTegelaar** [comment]
Yeah the required fields are really annoying :) glad its solved though!
