### ISSUE TITLE
How do I add/update UDF for a project?

### ISSUE THREAD

**Issue by AaronICT** [KelvinTegelaar/AutotaskAPI#36]
I cannot seem to figure out how to set values for user defined fields when creating a new project. Have guidance you can give would be greatly appreciated!
Thanks!
Aaron

**Comment by Andrew-CCC** [comment]
So I happened on the same problem tonight and figured it out.

UDFs come in as a PSCustomObject, so you can modify the properties just by calling them.  

When my $company comes in, the UDF for MY_UDF_NAME is empty, so to set it I just run

($company.userDefinedFields | where Name -eq "MY_UDF_NAME").value = $value 

And then pipe that back up to autotask as Kelvin put in his example

$company | Set-AutotaskAPIResource -resource Companies -id $company.id

And Bob's your uncle.

**Comment by AaronICT** [comment]
Thank you so much Andrew! That got me much closer! Do you happen to know a way to get a list of available values if the UDF is a list?
Thanks again!
Aaron

**Comment by Andrew-CCC** [comment]
just calling the variable in the Shell is enough to print it for me.  You could also just Write-Host $company.userDefinedFields which should show you what you have.
________________________________
