### ISSUE TITLE
[BUG] Set-AutotaskAPIResource does not work with TicketChecklistItemsChild

### ISSUE THREAD

**Issue by Serg86** [KelvinTegelaar/AutotaskAPI#43]
**Describe the bug**
Set-AutotaskAPIResource does not work with TicketChecklistItemsChild, perhaps with other resources as well.

**To Reproduce**
PS :> Set-AutotaskAPIResource -ID $ParentTicketID -Resource TicketChecklistItemsChild -body $ChecklistItemBody

**Expected behavior**
Modifications to the checklist item in the ticket.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PowerShell version: V5.1
 - Version: installed from gallery

**Additional context**
For debugging purposes I modified the Set-AutotaskAPIResource.ps1 file to output the $ResourceURL and it appears that the parentID is not being applied. I then modified the Invoke-RestMethod line to replace the parentId manually:

```Powershell
Invoke-RestMethod -Uri "$($Script:AutotaskBaseURI)/$($ResourceURL.Replace("{parentId}",$ID))" -headers $Headers -Body $SendingBody -Method Patch
```

This resulted in successful Api responses and the checklist items were modified correctly.

**Comment by krankin-ddc** [comment]
I can confirm this is also happening when trying to submit TicketNotesChild resources as well, the parentID is not being applied.

**Comment by Serg86** [comment]
I created a new module because this seemed unfinished and abandoned: https://www.powershellgallery.com/packages/AutotaskRestAPI/0.1

**Comment by KelvinTegelaar** [comment]
Fixed.
