### ISSUE TITLE
[BUG] Unable to query companies with "ID"

### ISSUE THREAD

**Issue by abdealikhurrum** [KelvinTegelaar/AutotaskAPI#46]
**Describe the bug**
I am unable to query company objects using the -id parameter in get-autotaskapiresource
**To Reproduce**
Get-AutotaskAPIResource -id "$companyid"  -Resource 'Companies' -verbose

**Expected behavior**
For the API to return an Autotask object with the company details. It works using simplesearch: Get-AutotaskAPIResource -simplesearch "id eq $companyid"  -Resource 'Companies' -verbose

**Screenshots**
![image](https://user-images.githubusercontent.com/974880/193628174-82538acb-f4b7-44b5-8e58-b6cc6a384ecb.png)
**Desktop (please complete the following information):**
 - OS: Windows 10 
 - PowerShell version: V5.1
 - Version 1.2.1

**Comment by KelvinTegelaar** [comment]
In your screenshot $CompanyId is an object with 'index' and 'name', and not an integer it expects.

**Comment by abdealikhurrum** [comment]
Getting the same error when inputting the ID directly:
![image](https://user-images.githubusercontent.com/974880/193634974-f495e87e-ad74-47d4-b48d-08be8346a7ce.png)

**Comment by KelvinTegelaar** [comment]
Fixed in dev, will be uploading today.
